name: Process features Alterados

on:
  push:
    branches:
      - main
    paths:
      - 'features/**'

  pull_request:
    branches:
      - main
    paths:
      - 'features/**'

jobs:
  select-file:
    uses: ./.github/workflows/select_changed_files.yml

  process-features:
    needs: select-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Install python dependencies
        run: |
          sudo apt update && sudo apt install -y python3 python3-pip
          pip install requests

      - name: Process changed files
        env:
          CHANGED_FILES: ${{ needs.select-file.outputs.changed_files }}
        run: |
          echo "Files to process: $CHANGED_FILES"

          for dados_file in $(echo $CHANGED_FILES | jq -r '.[]'); do
            config_file=$(echo "$dados_file" | sed 's/dados/config/g')
            if [[ -f "$config_file" ]]; then
              echo "Processing $dados_file com $config_file ..."
              python3 scripts/process_feature.py "$dados_file" "$config_file"
            else
              echo "Configuration file not found for: $dados_file"
            fi
          done
