name: Select changed files

on:
  workflow_call:
    outputs:
      changed_files:
        description: "List changed files"
        value: ${{ jobs.get_changed_files.outputs.changed_files }}

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 🚀 Garante acesso ao histórico de commits

      - name: Select changed files
        id: changed-files
        run: |
          BASE_BRANCH="origin/main"
          FILES=$(git diff --name-only $BASE_BRANCH...HEAD | grep 'features/.*/dados.*json' || true)

          echo "Files changed:"
          echo "$FILES"

          # Formatar como JSON para saída do workflow
          echo "modified_files=$(echo "$FILES" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
          echo "modified_files=$(echo "$FILES" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

